/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/chicken_tender.glb --typescript 
Author: UmangRank (https://sketchfab.com/UmangRank)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/chicken-tender-4db3246ae7914c37b29fbd1e75590cc0
Title: Chicken Tender
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/chicken_tender.glb')
  return (
    <group {...props} dispose={null}>
      <group scale={0.01}>
        <mesh geometry={nodes.mesh_base_material_0.geometry} material={materials.base_material} scale={166.927} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/chicken_tender.glb')
