/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kfc_bucket.glb --typescript
Author: YouniqueĪdeaStudio (https://sketchfab.com/sinnervoncrawsz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kfc-bucket-8a0260504a924b17a4196634ae4febc2
Title: KFC BUCKET

*/

import * as React from "react";
import * as THREE from "three";
import { useGLTF, useTexture } from "@react-three/drei";

const LABEL_ROTATION = -0.01;
const WALL_V_MIN = 0.74;
const WALL_V_MAX = 0.85;

export function Model(props) {
  const { nodes, materials } = useGLTF("/models/kfc_bucket.glb");
  const wrapMap = useTexture("/textures/utopia-bucket-wrap.jpg");

  const [bodyMaterial, bandMaterial] = React.useMemo(() => {
    const makeWrapTexture = () => {
      const tex = wrapMap.clone();
      tex.needsUpdate = true;
      tex.colorSpace = THREE.SRGBColorSpace;
      tex.flipY = false;
      tex.wrapS = THREE.RepeatWrapping;
      tex.wrapT = THREE.ClampToEdgeWrapping;
      tex.offset.x = LABEL_ROTATION;
      tex.repeat.y = 1 / (WALL_V_MAX - WALL_V_MIN);
      tex.offset.y = -WALL_V_MIN / (WALL_V_MAX - WALL_V_MIN);
      tex.anisotropy = 16;
      return tex;
    };

    const body = materials["Material.007"].clone();
    body.map = makeWrapTexture();
    body.color.set("#ffffff");

    const band = materials["Material.008"].clone();
    band.map = makeWrapTexture();
    band.color.set("#ffffff");

    return [body, band];
  }, [wrapMap, materials]);

  return (
    <group {...props} dispose={null}>
      <group rotation={[-1.906, -0.28, -0.025]} scale={0.007}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group
            position={[0, 1032.892, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100000}
          >
            <mesh
              geometry={nodes.baza005_Material007_0.geometry}
              material={bodyMaterial}
              receiveShadow
            />
            <mesh
              geometry={nodes.baza005_Material008_0.geometry}
              material={bandMaterial}
              receiveShadow
            />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/kfc_bucket.glb");
useTexture.preload("/textures/utopia-bucket-wrap.jpg");
