/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/kfc_bucket.glb --typescript 
Author: YouniqueĪdeaStudio (https://sketchfab.com/sinnervoncrawsz)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kfc-bucket-8a0260504a924b17a4196634ae4febc2
Title: KFC BUCKET
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/models/kfc_bucket.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-1.906, -0.28, -0.025]} scale={0.007}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[0, 1032.892, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100000}>
            <mesh geometry={nodes.baza005_Material007_0.geometry} material={materials['Material.007']} />
            <mesh geometry={nodes.baza005_Material008_0.geometry} material={materials['Material.008']} />
          </group>
          <mesh geometry={nodes.stamp001_Material005_0.geometry} material={materials['Material.005']} position={[16.529, 1811.255, 834.954]} rotation={[-Math.PI / 2, 0, 0]} scale={76165.422} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/kfc_bucket.glb')
