/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/krispy_fried_chicken.glb --typescript 
Author: aaa888 (https://sketchfab.com/aaa888)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/krispy-fried-chicken-486c17037e7e41aa95044411bb77887c
Title: Krispy Fried Chicken
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function Model(props) {
  const { nodes, materials } = useGLTF("/models/krispy_fried_chicken.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Object_2.geometry}
        material={materials["Material.001"]}
        rotation={[1.77, -0.501, 0.097]}
      />
    </group>
  );
}

useGLTF.preload("/models/krispy_fried_chicken.glb");
